### ISSUE TITLE
Some questions about details of dataset

### ISSUE THREAD

**Issue by csxyhe** [RaymondLZhou/deepDeband#1]
I have downloaded your dataset. It's an excellent dataset. But I have some questions on it. 
1. The dataset only includes 51420 pairs, but not 51490. Are there some mistakes?
2. Could you give some specific tips on how to partition the whole dataset into training, validation, testing three parts as your paper's description? I mean to partition it as Table 1 given in your paper.
I would be honored if you could reply to me. Thanks!

**Comment by RaymondLZhou** [comment]
Thanks for reaching out!

   1. The dataset there should be the most up to date I have - not sure why
   there's a difference, but what's uploaded is the most recent
   2. I'd recommend partitioning it so that for any image, all of its
   patches are either in the training, validation, or test set (we don't want
   patches from the same image in both training and validation, for example).
   Other than that, the images are pretty diverse in terms of visual content
   so there should be a good balance already regardless of how you split the
   patches
